table calculations
	lineageTag: 3d8da6de-16ad-459e-bb82-a563865587cb

	measure actual_next_week = SUM(predictions_evaluation[actual_next_week_revenue])
		displayFolder: pred_evaluation
		lineageTag: 52f47493-6e4f-4eb9-a5e8-22f270262757

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure pred_next_week = SUM(predictions_evaluation[prediction_next_week_revenue])
		displayFolder: pred_evaluation
		lineageTag: fe8e7bf5-219f-4410-bae1-5ba189f07585

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure model_residuals = SUM(predictions_evaluation[residuals])
		displayFolder: pred_evaluation
		lineageTag: 2e5a6d72-637f-43bb-8539-9880e14a36c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure viz_data_loss = 0.1 - VALUES(pipeline_health[data_loss_percentage])
		lineageTag: 3d1040d9-75be-4160-9c91-02b3f58545bb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition calculations = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

