name: CI/CD - Dataform Pipeline

on:
  pull_request:
    branches: [main]
    paths:
      - 'definitions/**'
      - 'includes/**'
      - 'workflow_settings.yaml'
      - '.github/workflows/ci-cd-dataform.yml'
  push:
    branches: [main]
    paths:
      - 'definitions/**'
      - 'includes/**'
      - 'workflow_settings.yaml'
      - '.github/workflows/ci-cd-dataform.yml'

  # Manual run
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dataform CLI
        run: npm install -g @dataform/cli

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.DEPLOYER_SA_EMAIL }}

      - name: Inject Dataform Credentials File
        run: |
          jq -n \
            --arg projectId "${{ secrets.GCP_PROJECT_ID }}" \
            --arg location "${{ secrets.DATASET_LOCATION }}" \
            '{
              projectId: $projectId,
              location: $location
            }' > .df-credentials.json

      - name: Install Project Dependencies
        run: dataform install

      - name: Compile and Validate Execution
        run: |
          dataform compile
          dataform run --dry-run